[package]
name = "v0"
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "v0"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.18.0"