name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build & run tests
      run: |
        docker build -f docker/Dockerfile -t dialect/protocol:latest .
        docker build -f docker/Dockerfile.test -t dialect/protocol-test:latest .